-- modify columns (all here should be executed without errors)
ALTER TABLE builds MODIFY COLUMN fk_buildstatus INT(10) UNSIGNED NOT NULL AFTER fk_user;

ALTER TABLE towers
	MODIFY COLUMN id INT(10) UNSIGNED NOT NULL FIRST,
	MODIFY COLUMN unitcost INT(10) UNSIGNED NOT NULL AFTER mu,
	MODIFY COLUMN manacost INT(10) UNSIGNED NOT NULL AFTER unitcost,
	MODIFY COLUMN fk_class INT(10) UNSIGNED NOT NULL AFTER manacost;

ALTER TABLE towers
	MODIFY COLUMN id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE towers
	MODIFY COLUMN mu TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 AFTER id;

ALTER TABLE buildwaves
	MODIFY COLUMN fk_build INT(10) UNSIGNED NOT NULL AFTER name;

ALTER TABLE maps
	MODIFY COLUMN sort INT(10) UNSIGNED NOT NULL AFTER units,
	MODIFY COLUMN fk_mapcategory INT(10) UNSIGNED NOT NULL AFTER sort;

-- insert foreign keys (here can appear errors, execute step by step)
-- build_stats
ALTER TABLE build_stats ADD FOREIGN KEY (buildID) REFERENCES builds(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE build_stats ADD FOREIGN KEY (classID) REFERENCES classes(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- builds
ALTER TABLE builds ADD FOREIGN KEY (gamemodeID) REFERENCES gamemode(gamemodeID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE builds ADD FOREIGN KEY (map) REFERENCES maps(id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE builds ADD FOREIGN KEY (difficulty) REFERENCES difficulties(id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE builds ADD FOREIGN KEY (fk_buildstatus) REFERENCES buildstatuses(id) ON DELETE RESTRICT ON UPDATE CASCADE;

-- towers
ALTER TABLE towers ADD FOREIGN KEY (fk_class) REFERENCES classes (id) ON DELETE CASCADE ON UPDATE CASCADE;

-- placed
ALTER TABLE placed ADD FOREIGN KEY (fk_build) REFERENCES builds (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE placed ADD FOREIGN KEY (fk_tower) REFERENCES towers (id) ON DELETE CASCADE ON UPDATE CASCADE;

-- buildwaves
ALTER TABLE buildwaves ADD FOREIGN KEY (fk_build) REFERENCES builds (id) ON DELETE CASCADE ON UPDATE CASCADE;

-- maps
ALTER TABLE maps ADD FOREIGN KEY (fk_mapcategory) REFERENCES mapcategories (id) ON DELETE CASCADE ON UPDATE CASCADE;
