CREATE TABLE bug_report (
	reportID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	steamID VARCHAR(20) NOT NULL,
	time INT(10) UNSIGNED DEFAULT 0 NOT NULL,
	title VARCHAR(64) NOT NULL,
	description TEXT NOT NULL,
	status TINYINT(1) UNSIGNED DEFAULT 0 NOT NULL,
	PRIMARY KEY (reportID)
);